### ISSUE TITLE
This socket was already closed

### ISSUE THREAD

**Issue by Fuyukai** [python-trio/trio-amqp#1]
```
Traceback (most recent call last):
  File "/home/laura/dev/discord/umbelli/umbelli/launcher.py", line 47, in <module>
    sys.exit(main())
  File "/home/laura/dev/discord/umbelli/umbelli/launcher.py", line 33, in main
    trio.run(run_master_node, config_file)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 1225, in run
    return result.unwrap()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_result.py", line 119, in unwrap
    raise self.error
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 923, in init
    self.entry_queue.spawn()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/dev/discord/umbelli/umbelli/master/__init__.py", line 46, in run_master_node
    await node._closed.wait()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/dev/discord/umbelli/umbelli/master/__init__.py", line 32, in open_master_node
    await node.close()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/__init__.py", line 45, in connect_from_url
    yield amqp
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/protocol.py", line 641, in connect_amqp
    amqp._cancel_all()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/protocol.py", line 482, in _reader_loop
    frame = await self.get_frame()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/protocol.py", line 395, in get_frame
    await frame.read_frame()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/frame.py", line 464, in read_frame
    data = await self._readexactly(7)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/frame.py", line 453, in _readexactly
    d = await self.reader.receive_some(length - len(data))
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_highlevel_socket.py", line 140, in receive_some
    return await self.socket.recv(max_bytes)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_highlevel_socket.py", line 31, in _translate_socket_errors_to_stream_errors
    raise ClosedStreamError("this socket was already closed") from None
trio.ClosedStreamError: this socket was already closed
```

Getting a lot of this spam; presumably it's obscuring an actual error.

**Comment by smurfix** [comment]
Ah, yes. Closing the connection cancels all tasks *except* for the reader, so I need to catch the error in there.

Should be fixed, v0.2.5 tagged and uploaded.

**Comment by Fuyukai** [comment]
The problem seems to persist on the newer version, this time coming from `_writer_loop`:

```
  File "/home/laura/dev/discord/umbelli/umbelli/master/__init__.py", line 33, in open_master_node
    pass
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/__init__.py", line 45, in connect_from_url
    yield amqp
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/protocol.py", line 645, in connect_amqp
    amqp._cancel_all()
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_util.py", line 109, in __aexit__
    await self._agen.asend(None)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 274, in asend
    return await self._do_it(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 290, in _do_it
    return await ANextIter(self._it, start_fn, *args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 202, in send
    return self._invoke(self._it.send, value)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
    result = fn(*args)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_multierror.py", line 144, in __exit__
    raise filtered_exc
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 203, in open_cancel_scope
    yield scope
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 318, in open_nursery
    await nursery._nested_child_finished(nested_child_exc)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 427, in _nested_child_finished
    raise MultiError(self._pending_excs)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_core/_run.py", line 1334, in run_impl
    msg = task.coro.send(next_send)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio_amqp/protocol.py", line 202, in _writer_loop
    await self._stream.send_all(f)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_highlevel_socket.py", line 117, in send_all
    total_sent += sent
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/laura/.local/share/virtualenvs/umbelli-SAq8Y3LW/lib/python3.6/site-packages/trio/_highlevel_socket.py", line 31, in _translate_socket_errors_to_stream_errors
    raise ClosedStreamError("this socket was already closed") from None
trio.ClosedStreamError: this socket was already closed
```

**Comment by smurfix** [comment]
OK, 0.2.6.
